

import "./globals.css";
import Nav from "./api/auth/nav";
import { Roboto } from "next/font/google";
import QuaryWrapper from "./quaryWrapper";


// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };
const roboto = Roboto({
  subsets: ["latin"],
  weight: ["400", "700"],
  variable: "--font-roboto",
});

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`mx-4 md:mx-46 xl:mx-96 ${roboto.variable} bg-gray-200`}>
       <QuaryWrapper>
       <Nav />
        {children}
       </QuaryWrapper>
      </body>
    </html>
  );
}

